### ISSUE TITLE
[Question] WasmContractsContractAddressStore usage

### ISSUE THREAD

**Issue by Mskalba** [terra-project/mantle#7]
Hello, we are getting balances of contractAddress for some accounts with query:

`{
  WasmContractsContractAddressStore(
    ContractAddress: "${contractAddress}"
    QueryMsg: "{ \\"balance\\": { \\"address\\": \\"${account}\\" }}"
  ) {
    Height
    Result
  }
}`

And I have couple of questions, maybe someone could help me with.

1. I am getting accounts for address from FCD:
`terra.wasm.contractQuery(contractAddress, {all_accounts: {limit: 30}});`

And for example for contactAddress: terra15gwkyepfc6xgca5t5zefzwy42uts8l2m4g40k6 I am getting account: terra1qqqvzaq2xnlkat4972eunq7dsndrm6zzvnk0hh

And then using above query to mantle I am receiving:  `balance:0` for that account on this contract. Is this not an error?

2. My second question is that, can I prepare a query to Mantle to get the balance for array of accounts? Is that possible, and if so, how to prepare such query?

**Comment by orthory** [comment]
Hey @Mskalba,

1. Not sure why you think this is an error; account `terra1qqqvzaq2xnlkat4972eunq7dsndrm6zzvnk0hh` really doesn't hold any token for contract `terra15gwkyepfc6xgca5t5zefzwy42uts8l2m4g40k6`. If you're asking why an account of balance `0` is being listed here, the `all_accounts` query simply iterates over the storage and gives you the list. This account may have had some tokens for this contract in the past, but now 0.

2. This specific usage `WasmContractsContractAddressStore` is no different than using lcd, so you'd need to do a separate balance query. There is no custom implementation for this.
